// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmziugjhbcxmfckddkns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teml1Z2poYmN4bWZja2Rka25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDUxNTAsImV4cCI6MjA3MDQ4MTE1MH0.XmjoQNTemwuLhrSQpcp4-wx-W5H72uOf_-iXsHQdZhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});